sudo: required
dist: xenial
language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true

before_install:
    - sudo apt-get update
    - sudo updatedb

install:
    - pip install ipython
    - pip install nose
    - pip install nose-exclude
    - pip install coverage
    - pip install coveralls
    - pip install pycodestyle
    - pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - pip install .

script:
    - python setup.py nosetests
    - pycodestyle pynet --ignore="E121,E123,E126,E226,E24,E704,E402,E731,E722,E741,W503,W504,W605"

after_success:
    - coveralls

