# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "doc/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Install system packages
          command: |
            sudo -E apt-get -yq update
            sudo apt install -y graphviz
            sudo apt install -y xdg-utils
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r doc/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "doc/requirements.txt" }}
      - run:
          name: Running CircleCI tests
          command: |
            . venv/bin/activate
            pip install torchvision==0.8.2
            pip install torchviz
            pip install joblib
            pip install -e .
            python .circleci/test_script.py
      - store_artifacts:
          path: test-reports
          destination: test-reports

